url: http://migsalazar/cs-course
baseurl: ""
topnav_title: Curso de Java
site_title:
company_name: Mig Salazar
company_url: http://migsalazar.com
github_editme_path:

# host: 127.0.0.1
# port: 4000

exclude:
  - _site
  - _drafts/
  - .idea/

feedback_email: migsalazar.com

highlighter: rouge
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouges
